# Generated by Django 3.2.4 on 2021-06-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteID', models.CharField(max_length=6, verbose_name='Site ID')),
                ('SiteName', models.CharField(max_length=50, verbose_name='Site Name')),
                ('SiteManager', models.CharField(max_length=40, verbose_name='Site Manager')),
                ('SiteEngineer', models.CharField(max_length=40, verbose_name='Site Engineer')),
                ('Longitude', models.FloatField()),
                ('Latitude', models.FloatField()),
            ],
        ),
    ]
